---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: beets-dev

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    curl: :8337/stats
    delay: 10
    curl_opts: --header x-api-key:drone
    pipe: |
      tee /dev/stderr |
      grep -q '{"albums":0,"items":0}'
    repo: beets-dev
    verbose: true

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: beets-dev
    repo: spritsail/beets
    tags:
    - latest
    - '%label io.spritsail.version.beets | %auto'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - tag

---
kind: signature
hmac: ac8c82ac2588411b5d767236bf1f13b87b3757ea7786471ccedf130962d7f2bf

...
