pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: beets-dev

  test:
    image: spritsail/docker-test
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: beets-dev
    delay: 5
    curl: :8337/stats
    pipe: grep -q '{"albums":0,"items":0}'

  publish:
    image: spritsail/docker-publish
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    from: beets-dev
    repo: spritsail/beets
    tags:
      - 'latest'
      - '%label io.spritsail.version.beets'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]

